[build]
  command = "echo 'no op'"
  publish = "example"

  [build.environment]
    YARN_FLAGS = "--frozen-lockfile"
    YARN_VERSION = "1.22.4"
    
[[plugins]]
package = "netlify-plugin-is-website-vulnerable"
