name: Submit plugin
on:
  release:
    types: [published]

jobs:
  submit-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - uses: netlify/submit-build-plugin-action@main
        with:
          # GitHub token with `public_repo` scope.
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
